apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
data:
  REACT_APP_BACKEND_URL: "http://localhost:32212"
  PUBLIC_URL: "/static/frontend"
  REACT_APP_BUILD_VERSION: "$(date +%s)"
  REACT_APP_SUPABASE_URL: "https://jxpsamnvzjziemtpziig.supabase.co"
