# Generated by Django 5.1.3 on 2025-02-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_remove_event_calendar_delete_calendar'),
    ]

    operations = [
    ]
