apiVersion: v1
kind: Secret
metadata:
  name: django-app-secrets
  namespace: default
type: Opaque
data:
  DJANGO_SECRET_KEY: ZWlua0BiPWF4N0BnNTFmYzcqeDctdHQodXRyXjhyODM2eWcyIyFqIzk3YncpISpvc2I=
  DJANGO_DEBUG: VHJ1ZQ==
  DJANGO_ALLOWED_HOSTS: bG9jYWxob3N0LDEyNy4wLjAuMSwxMC4xLjAuNDMsKg==
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXMuanhwc2FtbnZ6anppZW10cHppaWc=
  POSTGRES_PASSWORD: VXlyMDRXcDlJb0RkXmgz
  POSTGRES_HOST: YXdzLTAtZXUtY2VudHJhbC0xLnBvb2xlci5zdXBhYmFzZS5jb20=
  POSTGRES_PORT: NTQzMg==
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzLmp4cHNhbW52emp6aWVtdHB6aWlnOlV5cjA0V3A5SW9EZF5oM0Bhd3MtMC1ldS1jZW50cmFsLTEucG9vbGVyLnN1cGFiYXNlLmNvbTo1NDMyL3Bvc3RncmVz
