apiVersion: v1
kind: Secret
metadata:
  name: django-app-secrets
  namespace: default
type: Opaque
data:
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXQ0XiFrNiYpY2sqI2xiZXcjbzZ5cyE2KmlmOTBxdy0xJiQhaTUkLWdiPWoxK2M2eWpw
  POSTGRES_DB: cG9zdGdyZXMx
  POSTGRES_USER: cG9zdGdyZXMx
  POSTGRES_PASSWORD: cG9zdGdyZXMx
  POSTGRES_HOST: ZGI=
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzMTpwb3N0Z3JlczFAZGI6NTQzMi9wb3N0Z3JlczE=
  POSTGRES_PORT: NTQzMlNUT1JBR0VfUEFUSD0vZGF0YS9wb3N0Z3Jlcw==
