"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import json # Added for JSON parsing of React's asset-manifest.json
from pathlib import Path
from datetime import timedelta
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------------------------
# SECURITY
# ------------------------------------------------------------------------------------
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "fallback_secret")

# Fetch DJANGO_DEBUG from the environment (ConfigMap), defaulting to False if not found
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() in ("true", "1")

# Fetch DJANGO_ALLOWED_HOSTS from the environment (ConfigMap), defaulting to a safe fallback
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
# ------------------------------------------------------------------------------------

# ------------------------------------------------------------------------------------
# Application definition
# ------------------------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', # Added for Django REST Framework (DRF)
    'rest_framework_simplejwt', # Added for Django REST Framework Simple JWT
    'django_extensions',  # ✅ Add this to enable `show_urls`
    'corsheaders',
    'apps.scheduler', # Updated the path to include the apps folder
    'project_config',
    # Add your custom apps here
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",  # Must come after CorsMiddleware
]

ROOT_URLCONF = 'project_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'project_config/templates',  # Global templates
        ],
        'APP_DIRS': True, # ✅ Automatically finds templates inside installed apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'project_config.context_processors.asset_paths',  # ✅ Custom context processor for getting asset paths from asset-manifest
            ],
        },
    },
]

WSGI_APPLICATION = 'project_config.wsgi.application'


# ------------------------------------------------------------------------------------
# Database Configuration
# ------------------------------------------------------------------------------------
# You can either:
# 1) Use individual environment variables (POSTGRES_DB, POSTGRES_USER, etc.), or
# 2) Use a full DATABASE_URL environment variable (e.g., "postgresql://user:pass@db:5432/dbname").

# EXAMPLE 1: Using individual environment variables
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("POSTGRES_DB", "postgres"),
        'USER': os.getenv("POSTGRES_USER", "postgres"),
        'PASSWORD': os.getenv("POSTGRES_PASSWORD", ""),
        'HOST': os.getenv("POSTGRES_HOST", "db"),
        'PORT': os.getenv("POSTGRES_PORT", "5432"),
        'OPTIONS': {
            'sslmode': 'require',  # ✅ Ensures secure connection to Supabase
        },
    }
}

# EXAMPLE 2: Using DATABASE_URL (comment out EXAMPLE 1 if you choose this approach)
# import dj_database_url
# DATABASES = {
#     'default': dj_database_url.config(default="postgresql://postgres:@db:5432/postgres")
# }

# ------------------------------------------------------------------------------------
# Password validation
# ------------------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ------------------------------------------------------------------------------------
# Internationalization
# ------------------------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ------------------------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# ------------------------------------------------------------------------------------
# Specify the URL path that will be used to access Django static files
STATIC_URL = '/static/django/'  # ✅ This ensures Nginx knows how to find Django's static files

# The directory where collectstatic will place the files
STATIC_ROOT = os.getenv('STATIC_ROOT', BASE_DIR / 'global_static')

#Django's ManifestStaticFilesStorage appends a unique hash to the filenames of static files during the collectstatic process
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

STATICFILES_DIRS = [
    ("core", BASE_DIR / "project_config/static/core"),  # Core static files → /static/core/
    ("scheduler", BASE_DIR / "apps/scheduler/static/scheduler"),  # Scheduler static → /static/scheduler/
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Aiming to allow apps access
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    os.getenv("FRONTEND_URL", "http://localhost:3000"), # React Dev Server
    os.getenv("NGINX_URL", "http://192.168.49.2:32212"),  # If React is served from Nginx
]

# ✅ Allow dynamic frontend origin from environment variable
if "CODESPACE_NAME" in os.environ:
    codespace = f"https://{os.environ['CODESPACE_NAME']}-3000.app.github.dev"
    CORS_ALLOWED_ORIGINS.append(codespace)
else:
    # Add local development server to the list of trusted origins during local development.
    codespace = 'http://localhost:32212'

CORS_ALLOWED_ORIGINS.append(codespace)
CSRF_TRUSTED_ORIGINS = [codespace]  # Trust same origin for CSRF

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-custom-header",
]

SECURE_SSL_REDIRECT = False  # Disable HTTPS redirection for development

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # ✅ Requires login to access API
    ),
}

LOGIN_URL = reverse_lazy('scheduler_login')
LOGOUT_REDIRECT_URL = reverse_lazy('home')