apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx  # Correctly defined as a key-value map
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32212
