apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-pvc
spec:
  accessModes:
    - ReadWriteMany  # ✅ Allow multiple pods to access it if needed
  resources:
    requests:
      storage: 1Gi  # ✅ Adjust size as needed