apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce  # ✅ Ensures only one pod can use it at a time
  resources:
    requests:
      storage: 1Gi  # ✅ Set required storage size