apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staticfiles-pvc
spec:
  storageClassName: standard # Use "hostpath" for local storage & "standard" for codespaces
  accessModes:
    - ReadWriteOnce  # Ensure your environment supports RWX with local-path (usually best for single-node setups)
  resources:
    requests:
      storage: 1Gi