apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staticfiles-pvc
spec:
  storageClassName: hostpath # Use "hostpath" for local storage & "standard" for codespaces
  accessModes:
    - ReadWriteMany  # Ensure your environment supports RWX (ReadWriteMany) with local-path (usually best for single-node setups) RWO (ReadWriteOnce) with hostpath
  resources:
    requests:
      storage: 1Gi