# Generated by Django 5.1.5 on 2025-02-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_event_created_at_calendar_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='all_day',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
