# Generated by Django 5.1.3 on 2025-02-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_remove_event_all_day_remove_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='calendar',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
