apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      initContainers:
      - name: migrate  # ✅ Runs migrations before starting Django
        image: tytan22/django-app:1.0.20250207
        command: ["python", "manage.py", "migrate", "--noinput"]
        envFrom:
        - secretRef:
            name: django-app-secrets
        - configMapRef:
            name: django-config
        volumeMounts:
        - name: staticfiles-storage
          mountPath: /usr/share/nginx/html/static  # ✅ Django writes static here, Nginx reads from here

      containers:
      - name: django-container
        image: tytan22/django-app:1.0.20250207
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: django-app-secrets
        - configMapRef:
            name: django-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        volumeMounts:
        - name: staticfiles-storage
          mountPath: /usr/share/nginx/html/static  # ✅ Shared storage for static files

      volumes:
      - name: staticfiles-storage
        persistentVolumeClaim:
          claimName: staticfiles-pvc  # ✅ Shared PVC for static files