apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
      annotations:
        container-labels: |
          app=django-app
    spec:
      initContainers:
      - name: migrate
        image: tytan22/django-app:1.0.20250129
        command: ["python", "manage.py", "migrate", "--noinput"]
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: DJANGO_SECRET_KEY
        - name: DJANGO_DEBUG
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: DJANGO_DEBUG
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: DJANGO_ALLOWED_HOSTS
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: POSTGRES_PORT
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: DATABASE_URL

      containers:
      - name: django-container
        image: tytan22/django-app:1.0.20250129
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: DJANGO_SECRET_KEY
        - name: DJANGO_DEBUG
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: DJANGO_DEBUG
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: DJANGO_ALLOWED_HOSTS
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: POSTGRES_PORT
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-app-secrets
              key: DATABASE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        volumeMounts:
        - name: docs-volume
          mountPath: /final_project/docs  # Path inside the container

      volumes:
      - name: docs-volume
        hostPath:
          path: /run/desktop/mnt/host/d/Software/CS50W/final_project/docs  # Correct host path for Windows
          type: DirectoryOrCreate  # Creates the directory if it doesn’t exist
