apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      #initContainers:
      #  - name: migrate
      #    image: tytan22/django-app:1.0.20250219
      #    command: ["python", "/final_project/backend/manage.py", "migrate", "--noinput"]
      #    envFrom:
      #      - secretRef:
      #          name: consolidated-secrets
      #      - configMapRef:
      #          name: consolidated-config
      #    volumeMounts:
      #      - name: staticfiles-storage
      #        mountPath: /usr/share/nginx/html/django-static
      containers:
        - name: django-container
          image: tytan22/django-app:1.0.20250219
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: consolidated-secrets
            - configMapRef:
                name: consolidated-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
            - name: staticfiles-storage
              mountPath: /usr/share/nginx/html/django-static
      volumes:
        - name: staticfiles-storage
          persistentVolumeClaim:
            claimName: staticfiles-pvc  # PVC that holds static files