apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        # Use the frontend image directly for serving React files
        image: tytan22/frontend-app:1.0.20250212
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf # ✅ This replaces the default Nginx config
          subPath: nginx.conf
        - name: staticfiles-storage
          mountPath: /usr/share/nginx/html/django-static
          subPath: django-static
        - name: frontend-storage
          mountPath: /usr/share/nginx/html/frontend-static  # Correct path for React static files
          subPath: frontend-static
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: staticfiles-storage
        persistentVolumeClaim:
          claimName: staticfiles-pvc
      - name: frontend-storage
        persistentVolumeClaim:
          claimName: frontend-pvc