apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf  # ✅ Ensures only `nginx.conf` is mounted
        - name: staticfiles-storage
          mountPath: /usr/share/nginx/html/static
          subPath: static  # ✅ Ensures only `/static` subdirectory is mounted
        - name: frontend-storage
          mountPath: /usr/share/nginx/html
          subPath: frontend  # ✅ Ensures only `/frontend` subdirectory is mounted

      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: staticfiles-storage
        persistentVolumeClaim:
          claimName: staticfiles-pvc
      - name: frontend-storage
        persistentVolumeClaim:
          claimName: frontend-pvc