apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf  # Replace the main nginx.conf file
          subPath: nginx.conf
        - name: docs-volume
          mountPath: /usr/share/nginx/html  # Mount the docs folder to NGINX's default web root
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: docs-volume
        persistentVolumeClaim:
          claimName: docs-pvc