apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf  # ✅ Correctly mounting nginx.conf
          subPath: nginx.conf
        - name: staticfiles-storage # Define a volume (this is just a label)
          mountPath: /usr/share/nginx/html/static  # ✅ Match Nginx static serving path
        - name: frontend-storage
          mountPath: /usr/share/nginx/html/frontend  # ✅ Serve frontend from Ngin

      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: staticfiles-storage # Mount the PVC volume
        persistentVolumeClaim:
          claimName: staticfiles-pvc
      - name: frontend-storage
        persistentVolumeClaim:
          claimName: frontend-pvc  # ✅ Frontend React App storage