apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: static-files
          hostPath:
            path: /final_project/staticfiles  # 🔍 This must match Django's STATIC_ROOT
            type: DirectoryOrCreate  # ✅ Ensure directory is created if missing
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf  # Replace the main nginx.conf file
              subPath: nginx.conf
            - name: docs-volume
              mountPath: /usr/share/nginx/html  # Mount the docs folder to NGINX's default web root
            - name: static-files
              mountPath: /final_project/staticfiles  # ✅ Mount static files in Nginx
