apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 8000 # Port for your app inside Kubernetes
      targetPort: 8000 # Port your Django app is running on
      nodePort: 30007 # Optional: specify a NodePort (range: 30000–32767)
  type: NodePort
